	modLoader="javafml"
	loaderVersion="[31,)"
	license="GPL"
	
[[mods]]
	modId="draggableui"
	version="1.0"
	displayName="draggableui"
	displayURL=""
	issueTrackerURL=""
	logoFile=""
	credits=""
	authors="AreUThreateningMe"
	description='''
n'''

[[dependencies.draggableui]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.draggableui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"
